language: node_js
node_js:
  - "4.1"
before_script:
  - npm install gulp
  - npm install karma
  - npm install karma-jasmine
  - npm install karma-chrome-launcher
  - npm install karma-coverage
script: node_modules/karma/bin/karma start karma.coverage.js --single-run 